name: My Workflow 2
run-name: Kamal's Workflow 2
on:
    workflow_dispatch:
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: my sttep
              run: echo "hello this is my workflow 2"