name: My Workflow 2
run-name: Kamal's Workflow 2
on:
    workflow_dispatch:
env:
    MY_NAME: Kamal
    MY_JOB: Developer
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: my step4
              run: |
                  echo "hai i am ${{env.MY_NAME}} and i am a ${{env.MY_JOB}}"
                  echo "hai i am ${{env.MY_NAME}} and i am a ${{env.MY_JOB}}"
     job22:
        runs-on: ubuntu-latest
        steps:
            - name: my step4
              run: |
                  echo " ${{env.MY_NAME}} and i am a ${{env.MY_JOB}}"
                  echo "hai i am ${{env.MY_NAME}} and i am a ${{env.MY_JOB}}"
