name: My Workflow 1
on:
  #push:
  pull_request:
  workflow_dispatch:
  cron: '* * * * *' # Runs every day at midnight
    

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: my sttep
              run: echo "hello this is my workflow 1"
    