name: My Workflow 1
on:
  push:

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: echo "This is step 1 of job 1"
            - name: Step 2
              run: echo "This is step 2 of job 1"
            - run: |    
                echo "This is step 3.1 of job 1"
                echo "This is step 3.2 of job 1"

    job2:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: echo "This is step 1 of job 2"
            - name: Step 2
              run: echo "This is step 2 of job 2"                 